### ISSUE TITLE
[Checklist] - Add component for checklist to add to our main homepage component

### ISSUE THREAD

**Issue by kmorawski94** [Super-Sweet-Starbursts/agenda#22]
Tech Tasks:

- [ ] Set up Redux file to manage checklist state and export to our main Redux store
- [ ] Set up thunk for fetching all checklist items
- [ ] Set up thunk for adding checklist items
- [ ] Set up thunk for updating checklist items
- [ ] Set up thunk for deleting checklist items
- [ ] Set up React component for our checklist
