### ISSUE TITLE
[CheckList] - Set up DB and Api routes

### ISSUE THREAD

**Issue by kmorawski94** [Super-Sweet-Starbursts/agenda#23]
Tech Tasks:

- [x] Create API route to get all current logged in users list items
- [x] Create API route for user to create new user list items
- [x] Create API route for user to edit list items
- [x] Create API route for user to delete list items
